site:
  title: Personal Documentation Site
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://klopfy.ca/docs-site
  start_page: homelab::ansible.adoc
content:
  sources:
  - url: https://github.com/Klopfy/antora.git
    branches: HEAD
    tags: [alpha]
  - url: https://gitlab.com/antora/antora.git
    start_path: docs
    branches: v3.1.x
    edit_url: false

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''

ui:
  bundle:
    url: ./ui-bundle.zip

antora:
  extensions:
    - require: '@antora/lunr-extension'
