site:
  title: Personal Documentation Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://klopfy.ca/docs-site
  start_page: homelab::ansible.adoc
content:
  sources:
  - url: https://github.com/Klopfy/antora.git
    branches: HEAD
    tags: [v1]
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    #edit_url: false
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
    - require: '@antora/lunr-extension'
